import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Header from "@/components/header";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";
 import { dark } from '@clerk/themes'
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`bg-linear-to-br from-gray-950 via-zinc-900 to-stone-900 text-white`}
        suppressHydrationWarning
      >
        
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
        <ClerkProvider 
          appearance={{
            theme: dark,
          }}>
          <ConvexClientProvider>
              <Header/>
              <main className="relative min-h-screen container mx-auto pt-40 md:pt-32">
                <div className="pointer-events-none absolute inset-0 -z-10 overflow-hidden">
                    <div className="absolute top-0 left-1/4 w-96 h-96 bg-pink-600/20 rounded-full blur-3xl" />
                    <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-orange-600/20 rounded-full blur-3xl" />
                </div>
                <div className="relative z-10">{children}</div>   
                <footer>
                  <div className="relative z-10 py-10 text-center text-sm text-white/50">
                    © 2026 My Event Management App. All rights reserved.
                  </div>
                </footer>
                <Toaster richColors/>
              </main>
          </ConvexClientProvider>
        </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
